// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",

    // Chỉ định lệnh dùng để seed dữ liệu mặc định vào database
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
